### ISSUE TITLE
bro, you example is not virtual-scroller

### ISSUE THREAD

**Issue by RoseInHell** [saitergun/vue-virtual-scroller-example#1]
hi, bro. I had run your example, but it seem not virutal-scroller. The list DOM is real, it doesn't reuse DOM.

**Comment by saitergun** [comment]
thank you for feedback. virtualization works now.

**Comment by RoseInHell** [comment]
> thank you for feedback. virtualization works now.

wow, it works. thanks a lot!!! 😀

**Comment by saitergun** [comment]
enjoy!
